// react/spinride/src/screens/ForgotPassword.tsx
import React, {useState} from 'react';
import {useNavigate} from 'react-router-dom';

import {hooks} from '../hooks';
import {constants} from '../constants';
import {components} from '../components';

import styles from '../modules/forgot-password.module.scss';

export const ForgotPassword: React.FC = () => {
  hooks.useThemeColor('#F3F3F3');
  hooks.useBodyColor('#F3F3F3');

  const navigate = useNavigate();

  const [form, setForm] = useState({
    email: '',
  });

  const handleChangeField = (field: keyof typeof form, label: string) => {
    const result = window.prompt(`Enter your ${label}`, form[field]);
    if (result !== null) {
      setForm((prev) => ({...prev, [field]: result}));
    }
  };

  const renderHeader = () => {
    return (
      <components.Header
        title='Forgot password'
        showGoBack={true}
      />
    );
  };

  const renderContent = () => {
    return (
      <main className={styles.main}>
        <p className={`t16 ${styles.description}`}>
          Please enter your email address. You will receive a link to create a
          new password via email.
        </p>
        <components.InputField
          placeholder='cristinawolf@mail.com'
          containerStyle={{marginBottom: 14}}
          value={form.email}
          onClick={() => handleChangeField('email', 'email')}
          isValid={form.email.length > 0 && form.email.includes('@')}
        />
        <components.Button
          title='Send'
          onClick={() => {
            navigate(constants.routes.NEW_PASSWORD, {
              state: {email: form.email},
            });
          }}
        />
      </main>
    );
  };

  return (
    <components.MotionWrapper>
      <components.SafeAreaView>
        {renderHeader()}
        {renderContent()}
      </components.SafeAreaView>
    </components.MotionWrapper>
  );
};

// angular/spinride/src/app/screens/forgot-password/forgot-password.component.ts
import {Component, OnInit} from '@angular/core';

import {MetaService} from '../../services/meta.service';

@Component({
  selector: 'app-forgot-password',
  templateUrl: './forgot-password.component.html',
  styleUrl: './forgot-password.component.scss',
  standalone: false,
})
export class ForgotPasswordComponent implements OnInit {
  constructor(private metaService: MetaService) {}

  ngOnInit(): void {
    this.metaService.setThemeColor('#F6F9F9');
    this.metaService.setBackgroundColor('#F6F9F9');
  }
}

<app-header [showGoBack]="true" [title]="'Forgot password'" />

<main style="margin-left: 20px; margin-right: 20px; margin-top: 10px">
  <section
    style="
      background-color: var(--white-color);
      padding-top: 30px;
      padding-bottom: 30px;
      padding-left: 20px;
      padding-right: 20px;
      border-radius: 10px;
    "
  >
    <p class="t16" style="margin-bottom: 32px">
      Please enter your email address. You <br />
      will receive a link to create a new <br />
      password via email.
    </p>
    <app-input-field
      [check]="true"
      [type]="'email'"
      [placeholder]="'jordanhebert@mail.com'"
      [containerStyle]="{'margin-bottom': '16px'}"
    />
    <app-button [text]="'send'" [routerLink]="'/new-password'" />
  </section>
</main>
