// angular/spinride/src/app/screens/categories/categories.component.ts
import {Component, OnInit} from '@angular/core';

import {ApiService} from '../../services/api.service';
import {MetaService} from '../../services/meta.service';
import {CategoryModel} from '../../models/category.model';

@Component({
  selector: 'app-categories',
  standalone: false,
  templateUrl: './categories.component.html',
  styleUrl: './categories.component.scss',
})
export class CategoriesComponent implements OnInit {
  categories: CategoryModel[] = [];
  isLoading = true;

  constructor(
    private metaService: MetaService,
    private apiService: ApiService,
  ) {}

  ngOnInit(): void {
    this.setMeta();
    this.getCategories();
  }

  setMeta(): void {
    this.metaService.setThemeColor('#F3F3F3');
    this.metaService.setBackgroundColor('#F3F3F3');
  }

  getCategories(): void {
    this.apiService.getCategories().subscribe({
      next: data => (this.categories = data.categories),
      error: error => {
        console.error('Error fetching categories:', error);
        this.isLoading = false;
      },
      complete: () => (this.isLoading = false),
    });
  }
}

<app-header
  [showBurger]="true"
  [showBasket]="true"
  [showBorder]="true"
  [showSearch]="true"
/>

<main style="height: 100%; overflow-y: auto">
  <ul
    style="
      display: flex;
      flex-direction: row;
      flex-wrap: wrap;
      padding-left: 20px;
      padding-right: 20px;
      padding-top: 20px;
      padding-bottom: 20px;
      gap: 15px;
      justify-content: space-between;
    "
  >
    <li
      *ngFor="let category of categories; let i = index"
      [ngStyle]="{
        width: (i + 1) % 3 === 0 ? '100%' : 'calc(50% - 7.5px)',
      }"
      style="border-radius: 12px; overflow: hidden"
    >
      <a [routerLink]="['/shop']" style="position: relative; user-select: none">
        <img
          [src]="category.image"
          [alt]="category.category"
          style="height: auto; width: 100%; border-radius: 12px"
        />
        <div style="position: absolute; bottom: 20px; left: 20px; width: 100%">
          <h5 style="color: var(--white-color); white-space: nowrap">
            {{ category.category }}
          </h5>
        </div>
      </a>
    </li>
  </ul>
</main>

<app-bottom-tab-bar />

// react/spinride/src/screens/Categories.tsx
import React from 'react';

import {hooks} from '../hooks';
import {constants} from '../constants';
import {components} from '../components';

export const Categories: React.FC = () => {
  const {navigate} = hooks.useRouter();
  const {categories, loading, error} = hooks.useGetCategories();

  const renderHeader = () => {
    return (
      <components.Header
        showBurger={true}
        showBasket={true}
        showBorder={true}
      />
    );
  };

  const renderBottomBar = () => {
    return <components.BottomTabBar />;
  };

  const renderContent = () => {
    if (loading) return <components.Loader />;
    return (
      <main
        style={{
          paddingLeft: 20,
          paddingRight: 20,
          overflowY: 'auto',
          paddingTop: 'calc(var(--header-height) + 20px)',
          paddingBottom: 'calc(var(--bottom-tabbar-height) + 40px)',
        }}
      >
        <ul
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(2, 1fr)',
            gap: '15px',
          }}
        >
          {categories.map((item, index) => (
            <button
              key={item.id}
              style={{
                gridColumn: index % 3 === 2 ? 'span 2' : 'span 1',
                borderRadius: 12,
                overflow: 'hidden',
                position: 'relative',
              }}
              onClick={() => {
                navigate(constants.routes.SHOP);
              }}
            >
              <img
                src={item.image}
                style={{
                  width: '100%',
                  height: 'auto',
                  objectFit: 'cover',
                }}
              />
              <div
                style={{
                  position: 'absolute',
                  bottom: 0,
                  left: 0,
                  right: 0,
                  padding: 20,
                }}
              >
                <h5
                  className="number-of-lines-1"
                  style={{color: 'var(--white-color)'}}
                >
                  {item.category}
                </h5>
              </div>
            </button>
          ))}
        </ul>
      </main>
    );
  };

  return (
    <components.MotionWrapper>
      <components.SafeAreaView>
        {renderHeader()}
        {renderContent()}
        {renderBottomBar()}
      </components.SafeAreaView>
    </components.MotionWrapper>
  );
};
