// angular/spinride/src/app/screens/checkout/checkout.component.ts
import {Component, OnInit} from '@angular/core';

import {svg} from '../../../../public/assets/svg';
import {DishModel} from '../../models/dish.model';
import {CartService} from '../../services/cart.service';
import {MetaService} from '../../services/meta.service';

@Component({
  selector: 'app-checkout',
  templateUrl: './checkout.component.html',
  styleUrl: './checkout.component.scss',
  standalone: false,
})
export class CheckoutComponent implements OnInit {
  svg = svg;
  list: DishModel[] = [];
  total: number = 0;
  discount: number = 0;
  delivery: number = 0;

  constructor(
    private metaService: MetaService,
    private cartService: CartService,
  ) {}

  ngOnInit(): void {
    this.initializeMeta();
    this.initializeCartSubscription();
  }

  private initializeMeta(): void {
    this.metaService.setThemeColor('#F5FAFB');
    this.metaService.setBackgroundColor('#F5FAFB');
  }

  private initializeCartSubscription(): void {
    this.cartService.cartState$.subscribe(cart => {
      this.list = cart.list;
      this.total = cart.total;
      this.discount = cart.discount;
      this.delivery = cart.delivery;
    });
  }

  handleClick(event: Event): void {
    event.stopPropagation();
    event.preventDefault();
  }
}

<app-header [title]="'Checkout'" [showGoBack]="true" />
<div style="height: 10px"></div>

<main
  style="margin-left: 20px; margin-right: 20px; height: 100%; overflow-y: auto"
>
  <!-- my order -->
  <section
    style="
      padding: 20px;
      border-radius: 10px;
      border: 1px solid var(--main-turquoise);
      margin-bottom: 16px;
    "
  >
    <!-- my order & price-->
    <div
      style="
        display: flex;
        flex-direction: row;
        flex-direction: row;
        justify-content: space-between;
        margin-bottom: 20px;
        padding-bottom: 20px;
        border-bottom: 1px solid #dbe9f5;
      "
    >
      <h4 style="text-transform: capitalize">My order</h4>
      <h4>${{ total.toFixed(2) }}</h4>
    </div>
    <!-- dishes -->
    <ul style="margin-bottom: 6px">
      <li
        *ngFor="let dish of list; let i = index; let last = last"
        style="
          display: flex;
          flex-direction: row;
          align-items: center;
          justify-content: space-between;
        "
        [ngStyle]="{
          marginBottom: last ? '0px' : '10px',
        }"
      >
        <span class="t14">{{ dish.name }}</span>
        <span class="t14">{{ dish.quantity }} x ${{ dish.price }}</span>
      </li>
    </ul>
    <!-- discount & delivery -->
    <div
      style="
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 10px;
      "
    >
      <span class="t14">Discount</span>
      <span class="t14">${{ discount }}</span>
    </div>
    <div
      style="
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        align-items: center;
      "
    >
      <span class="t14">Delivery</span>
      <span class="t14">${{ delivery }}</span>
    </div>
  </section>

  <!-- Shipping details -->
  <section>
    <button
      style="
        background-color: var(--white-color);
        padding: 20px;
        border-radius: 10px;
        margin-bottom: 16px;
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
        width: 100%;
      "
      (click)="handleClick($event)"
    >
      <div style="display: flex; flex-direction: column; width: 100%">
        <span
          class="t14"
          style="
            margin-bottom: 10px;
            color: var(--main-color);
            font-weight: 500;
          "
        >
          Shipping Details
        </span>
        <span class="t12"> 8000 S Kirkland Ave, Chicago, IL 6065... </span>
      </div>
      <img src="{{ svg.rightArrow }}" alt="Edit" />
    </button>
  </section>

  <!-- payment method -->
  <section>
    <button
      style="
        background-color: var(--white-color);
        padding: 20px;
        border-radius: 10px;
        margin-bottom: 16px;
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
        width: 100%;
      "
      (click)="handleClick($event)"
    >
      <div style="display: flex; flex-direction: column; width: 100%">
        <span
          class="t14"
          style="
            margin-bottom: 10px;
            color: var(--main-color);
            font-weight: 500;
          "
        >
          Payment Method
        </span>
        <span class="t12">4947 **** **** 3157</span>
      </div>
      <img src="{{ svg.rightArrow }}" alt="Edit" />
    </button>
  </section>
</main>

<!-- button -->
<section style="padding: 20px">
  <app-button [routerLink]="'/order-successful'" [text]="'Confirm order'" />
</section>

// react/spinride/src/screens/Checkout.tsx
import React from 'react';

import {hooks} from '../hooks';
import {constants} from '../constants';
import {components} from '../components';
import {useAppSelector} from '../store';

export const Checkout: React.FC = () => {
  const {list: cart, total} = useAppSelector((state) => state.cartSlice);

  const {navigate} = hooks.useRouter();

  const renderHeader = () => {
    return (
      <components.Header showGoBack={true} title="Checkout" showBorder={true} />
    );
  };

  const renderContent = () => {
    return (
      <main
        style={{
          overflowY: 'auto',
          paddingTop: 'calc(var(--header-height) + 20px)',
          paddingBottom: 90,
          paddingLeft: 20,
          paddingRight: 20,
          display: 'flex',
          flexDirection: 'column',
        }}
      >
        {/* My order */}
        <section style={{marginBottom: 32}}>
          <div
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              marginBottom: 14,
            }}
          >
            <h4>My order</h4>
            <h4>${(total - 413).toLocaleString('en-US')}</h4>
          </div>
          <div
            style={{
              backgroundColor: 'var(--white-color)',
              padding: 20,
              borderRadius: 12,
            }}
          >
            <ul
              style={{
                display: 'flex',
                flexDirection: 'column',
                gap: 3,
                marginBottom: 3,
              }}
            >
              {cart.map((item) => (
                <li
                  key={item.id}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                  }}
                >
                  <span className="t14">{item.name}</span>
                  <span className="t14">
                    {item.quantity} x ${item.price.toLocaleString('en-US')}
                  </span>
                </li>
              ))}
            </ul>
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                marginBottom: 3,
              }}
            >
              <span className="t14">Discount</span>
              <span className="t14">-413</span>
            </div>
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
              }}
            >
              <span className="t14">Delivery</span>
              <span className="t14" style={{color: '#51BA74'}}>
                Free
              </span>
            </div>
          </div>
        </section>

        {/* My order */}
        <section>
          <div
            style={{
              marginBottom: 14,
            }}
          >
            <h4>Shipping & payment info</h4>
          </div>
          <div
            style={{
              backgroundColor: 'var(--white-color)',
              padding: 20,
              borderRadius: 12,
              display: 'flex',
              flexDirection: 'column',
              gap: 10,
            }}
          >
            <span className="t14">Darron Banks</span>
            <span className="t14">
              8000 S Kirkland Ave, Chicago, IL 6065...
            </span>
            <span className="t14">**** 4864</span>
          </div>
        </section>
      </main>
    );
  };

  const renderButton = () => {
    return (
      <section
        style={{
          paddingLeft: 20,
          paddingRight: 20,
          position: 'fixed',
          bottom: 'env(safe-area-inset-bottom)',
          left: 0,
          right: 0,
          backgroundColor: 'var(--anti-flash-white)',
          paddingTop: 20,
          paddingBottom: 20,
          maxWidth: 'var(--screen-width)',
          margin: '0 auto',
        }}
      >
        <components.Button
          title="Confirm order"
          onClick={() => {
            navigate(constants.routes.ORDER_SUCCESSFUL);
          }}
        />
      </section>
    );
  };

  return (
    <components.MotionWrapper>
      <components.SafeAreaView>
        {renderHeader()}
        {renderContent()}
        {renderButton()}
      </components.SafeAreaView>
    </components.MotionWrapper>
  );
};
