// angular/spinride/src/app/screens/info-saved/info-saved.component.ts
import {Component} from '@angular/core';

import {URLS} from '../../config';
import {svg} from '../../../../public/assets/svg';
import {MetaService} from '../../services/meta.service';

@Component({
  selector: 'app-info-saved',
  templateUrl: './info-saved.component.html',
  styleUrl: './info-saved.component.scss',
  standalone: false,
})
export class InfoSavedComponent {
  svg = svg;
  URLS = URLS;

  constructor(private metaService: MetaService) {}

  ngOnInit(): void {
    this.setMeta();
  }

  private setMeta(): void {
    this.metaService.setThemeColor('#161E2F');
    this.metaService.setBackgroundColor('#161E2F');
  }
}

<app-header />

<img
  src="./assets/bg/01.png"
  alt="Add to cart"
  style="position: absolute; width: 100%; height: auto; z-index: -1"
/>

<main
  style="height: 100%; overflow-y: auto; margin-left: 20px; margin-right: 20px"
>
  <section
    style="
      height: 100%;
      display: flex;
      justify-content: center;
      flex-direction: column;
      padding-bottom: 20%;
    "
  >
    <img
      [alt]="'info saved'"
      [className]="'status-image'"
      [src]="svg.pocket"
      style="width: 180px"
    />
    <h2
      style="
        text-align: center;
        margin-bottom: 14px;
        text-transform: capitalize;
        color: var(--white-color);
        text-transform: capitalize;
      "
    >
      Info Saved!
    </h2>
    <p
      class="t16"
      style="text-align: center; color: #c3cde0; margin-bottom: 30px"
    >
      Your personal information has been <br />
      securely stored.
    </p>
    <div style="max-width: 170px; margin: 0 auto; width: 100%">
      <app-button [text]="'Done'" [routerLink]="'/profile'" />
    </div>
  </section>
</main>

// react/spinride/src/screens/InfoSaved.tsx
import React from 'react';
import {useNavigate} from 'react-router-dom';

import {hooks} from '../hooks';
import {svg} from '../assets/svg';
import {constants} from '../constants';
import {components} from '../components';

export const InfoSaved: React.FC = () => {
  const navigate = useNavigate();
  hooks.useThemeColor('#161e2f');
  hooks.useBodyColor('#161e2f');

  const renderBackground = () => {
    return (
      <img
        src={constants.images.bg01}
        alt='bg'
        style={{
          position: 'fixed',
          width: '100%',
          height: 'auto',
          zIndex: 1,
          maxWidth: 'var(--screen-width)',
          margin: '0 auto',
        }}
      />
    );
  };

  const renderContent = () => {
    return (
      <main
        style={{
          padding: 20,
          zIndex: 2,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          overflowY: 'auto',
          height: '100%',
          paddingBottom: '20%',
        }}
      >
        <div style={{marginBottom: 14}}>
          <svg.PocketSvg />
        </div>
        <h2
          style={{
            color: 'var(--white-color)',
            textTransform: 'capitalize',
            marginBottom: 14,
          }}
        >
          Info Saved!
        </h2>
        <p
          style={{
            maxWidth: 290,
            textAlign: 'center',
            color: '#C3CDE0',
            marginBottom: 30,
          }}
          className='t16'
        >
          Your personal information has been securely stored.
        </p>
        <components.Button
          title='Done'
          onClick={() => navigate(-1)}
          containerStyle={{maxWidth: 170}}
        />
      </main>
    );
  };

  return (
    <components.MotionWrapper>
      <components.SafeAreaView>
        {renderBackground()}
        {renderContent()}
      </components.SafeAreaView>
    </components.MotionWrapper>
  );
};
