// angular/spinride/src/app/screens/leave-a-review/leave-a-review.component.ts
import {Component} from '@angular/core';

import {URLS} from '@config/index';
import {svg} from '@svg/index';
import {MetaService} from '@services/meta.service';

@Component({
  selector: 'app-leave-a-review',
  standalone: false,
  templateUrl: './leave-a-review.component.html',
  styleUrl: './leave-a-review.component.scss',
})
export class LeaveAReviewComponent {
  svg = svg;
  URLS = URLS;
  value: string = 'Enter your review here...';
  constructor(private metaService: MetaService) {}

  ngOnInit(): void {
    this.setMeta();
  }

  setMeta(): void {
    this.metaService.setThemeColor('#161E2F');
    this.metaService.setBackgroundColor('#161E2F');
  }

  openKeyboard() {
    const result = prompt('Enter text:', this.value);
    if (result !== null) {
      this.value = result;
    }
  }
}

<img
  src="./assets/bg/01.png"
  alt="Add to cart"
  style="position: absolute; width: 100%; height: auto; z-index: -1"
/>

<app-header
  [showGoBack]="true"
  [title]="'Leave a review'"
  [goBackColor]="'white'"
  [titleStyle]="{color: 'var(--white-color)'}"
/>

<main
  style="
    overflow-y: auto;
    height: 100%;
    margin-left: 20px;
    margin-right: 20px;
    padding-bottom: 10px;
    padding-top: 10px;
    -webkit-overflow-scrolling: touch;
    scroll-behavior: smooth;
    user-select: none;
    padding-top: 10%;
    padding-bottom: 10%;
  "
>
  <img
    [alt]="'info saved'"
    [className]="'status-image'"
    [src]="svg.messageCircle"
    style="width: 180px"
  />
  <h2
    style="text-transform: capitalize; text-align: center; margin-bottom: 20px"
  >
    Please rate the quality of <br />
    service for the order!
  </h2>
  <div style="margin-bottom: 20px">
    <app-rating-stars />
  </div>
  <p
    style="
      text-align: center;
      max-width: 300px;
      width: 100%;
      margin: 0 auto;
      margin-bottom: 30px;
      color: #c3cde0;
    "
    class="t16"
  >
    Your comments and suggestions help us improve the service quality better!
  </p>
  <div
    style="
      height: 127px;
      width: 100%;
      border-radius: 10px;
      padding: 14px;
      font-size: 16px;
      font-family: 'League Spartan';
      color: var(--main-color);
      margin-bottom: 16px;
      background-color: var(--white-color);
      border: none;
      font-family: var(--dm-sans);
      font-size: 16px;
    "
    (click)="$event.stopPropagation(); $event.preventDefault(); openKeyboard()"
  >
    <span style="font-size: 16px; color: var(--text-color)">
      {{ value }}
    </span>
  </div>
  <app-button [text]="'submit'" [routerLink]="'/home'" />
</main>

// react/spinride/src/screens/LeaveAReview.tsx
import React, {useState} from 'react';

import {hooks} from '../hooks';
import {svg} from '../assets/svg';
import {constants} from '../constants';
import {components} from '../components';

export const LeaveAReview: React.FC = () => {
  hooks.useThemeColor('#161e2f');
  hooks.useBodyColor('#161e2f');

  const {navigate} = hooks.useRouter();

  const [form, setForm] = useState({
    comment: '',
  });

  const handleChangeField = (field: keyof typeof form, label: string) => {
    const result = window.prompt(`Enter your ${label}`, form[field]);
    if (result !== null) {
      setForm((prev) => ({...prev, [field]: result}));
    }
  };

  const renderBackground = () => {
    return (
      <img
        src={constants.images.bg01}
        alt="bg"
        style={{
          position: 'fixed',
          width: '100%',
          height: 'auto',
          zIndex: 1,
          maxWidth: 'var(--screen-width)',
          margin: '0 auto',
        }}
      />
    );
  };

  const renderHeader = () => {
    return (
      <components.Header
        showGoBack={true}
        title="Leave a review"
        containerStyle={{
          backgroundColor: '#161e2f',
        }}
        titleStyle={{color: 'var(--white-color)'}}
        goBackColor="var(--white-color)"
      />
    );
  };

  const renderContent = () => {
    return (
      <main
        style={{
          overflowY: 'auto',
          // height: '100%',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          paddingTop: 'calc(var(--header-height) + 0px)',
          paddingBottom: 20,
          zIndex: 2,
          paddingLeft: 20,
          paddingRight: 20,
          marginTop: '6%',
        }}
      >
        <div style={{marginBottom: 14}}>
          <svg.MessageCircleSvg />
        </div>
        <h2
          style={{
            color: 'var(--white-color)',
            textTransform: 'capitalize',
            marginBottom: 14,
            maxWidth: 303,
            textAlign: 'center',
          }}
        >
          Please rate the quality of service for the order!
        </h2>
        <p
          style={{
            maxWidth: 335,
            textAlign: 'center',
            color: '#C3CDE0',
            marginBottom: 30,
          }}
          className="t16"
        >
          Your comments and suggestions help us improve the service quality
          better!
        </p>
        <components.InputField
          placeholder="Enter your comment"
          containerStyle={{
            minHeight: 140,
            borderRadius: 12,
            alignItems: 'flex-start',
            paddingTop: 11,
            marginBottom: 14,
          }}
          value={form.comment}
          onClick={() => handleChangeField('comment', 'comment')}
        />
        <components.Button
          title="submit"
          onClick={() => {
            navigate(-1);
          }}
        />
      </main>
    );
  };

  return (
    <components.MotionWrapper>
      <components.SafeAreaView>
        {renderBackground()}
        {renderHeader()}
        {renderContent()}
      </components.SafeAreaView>
    </components.MotionWrapper>
  );
};
