// angular/spinride/src/app/screens/order-failed/order-failed.component.ts
import {Component} from '@angular/core';

import {svg} from '@svg/index';
import {URLS} from '../../config';
import {MetaService} from '../../services/meta.service';

@Component({
  selector: 'app-order-failed',
  templateUrl: './order-failed.component.html',
  styleUrl: './order-failed.component.scss',
  standalone: false,
})
export class OrderFailedComponent {
  svg = svg;
  URLS = URLS;

  constructor(private metaService: MetaService) {}

  ngOnInit(): void {
    this.metaService.setThemeColor('#161E2F');
    this.metaService.setBackgroundColor('#161E2F');
  }
}

<img
  alt="bg"
  src="./assets/bg/01.png"
  style="position: absolute; width: 100%; height: auto; z-index: -1"
/>

<main style="height: 100%; overflow-y: auto; -webkit-overflow-scrolling: touch">
  <section
    style="
      display: flex;
      justify-content: center;
      flex-direction: column;
      height: 100%;
      padding-left: 20px;
      padding-right: 20px;
    "
  >
    <img
      [alt]="'info saved'"
      [className]="'status-image'"
      [src]="svg.checkCircle"
      style="width: 180px"
    />
    <h2
      style="text-align: center; margin-bottom: 4%; text-transform: capitalize"
    >
      Your order has failed!
    </h2>
    <p
      style="
        text-align: center;
        margin-bottom: 30px;
        color: #c3cde0;
        font-size: 16px;
        line-height: 1.7;
      "
    >
      Something went wrong. Please try <br />
      again to continue your order.
    </p>
    <div
      style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px"
    >
      <app-button
        [text]="'my profile'"
        [colorScheme]="'secondary'"
        [routerLink]="['/profile']"
      />
      <app-button [text]="'try again'" [routerLink]="['/order']" />
    </div>
  </section>
</main>

// react/spinride/src/screens/OrderFailed.tsx
import React from 'react';
import {useNavigate} from 'react-router-dom';

import {hooks} from '../hooks';
import {svg} from '../assets/svg';
import {constants} from '../constants';
import bg from '../assets/bg/01.png';
import {components} from '../components';

export const OrderFailed: React.FC = () => {
  const navigate = useNavigate();
  hooks.useThemeColor('#161e2f');
  hooks.useBodyColor('#161e2f');

  const renderBackground = () => {
    return (
      <img
        src={bg}
        alt='bg'
        style={{
          position: 'fixed',
          width: '100%',
          height: 'auto',
          zIndex: 1,
          maxWidth: 'var(--screen-width)',
          margin: '0 auto',
        }}
      />
    );
  };

  const renderContent = () => {
    return (
      <main
        style={{
          padding: 20,
          zIndex: 2,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          overflowY: 'auto',
          height: '100%',
          paddingBottom: '20%',
        }}
      >
        <div style={{marginBottom: 14}}>
          <svg.FailedCrossSvg />
        </div>
        <h2
          style={{
            color: 'var(--white-color)',
            textTransform: 'capitalize',
            marginBottom: 14,
          }}
        >
          Your order has failed!
        </h2>
        <p
          style={{
            maxWidth: 290,
            textAlign: 'center',
            color: '#C3CDE0',
            marginBottom: 30,
          }}
          className='t16'
        >
          Something went wrong. Please try again to continue your order.
        </p>
        <div
          style={{
            display: 'grid',
            gap: 15,
            width: '100%',
            gridTemplateColumns: 'repeat(2, 1fr)',
          }}
        >
          <components.Button
            title='my profile'
            colorScheme='secondary'
            onClick={() => navigate(constants.routes.SIGN_IN)}
          />
          <components.Button
            title='try again'
            onClick={() => navigate(-1)}
          />
        </div>
      </main>
    );
  };

  return (
    <components.MotionWrapper>
      <components.SafeAreaView>
        {renderBackground()}
        {renderContent()}
      </components.SafeAreaView>
    </components.MotionWrapper>
  );
};
