// angular/spinride/src/app/screens/sign-out/sign-out.component.ts
import {Component, OnInit} from '@angular/core';

import {svg} from '../../../../public/assets/svg';
import {MetaService} from '../../services/meta.service';

@Component({
  selector: 'app-sign-out',
  standalone: false,
  templateUrl: './sign-out.component.html',
  styleUrl: './sign-out.component.scss',
})
export class SignOutComponent implements OnInit {
  svg = svg;

  constructor(private metaService: MetaService) {}

  ngOnInit(): void {
    this.setMeta();
  }

  setMeta(): void {
    this.metaService.setThemeColor('#161E2F');
    this.metaService.setBackgroundColor('#161E2F');
  }
}

<img
  alt="Background Image"
  src="./assets/bg/01.png"
  style="position: absolute; width: 100%; height: auto; z-index: -1"
/>

<main
  style="height: 100%; overflow-y: auto; margin-left: 20px; margin-right: 20px"
>
  <section
    style="
      height: 100%;
      display: flex;
      justify-content: center;
      flex-direction: column;
      padding-bottom: 20%;
    "
  >
    <img
      [alt]="'log out'"
      [src]="svg.logOut"
      style="width: 180px; margin: 0 auto; margin-bottom: 20px"
    />
    <h2
      style="
        text-align: center;
        margin-bottom: 14px;
        text-transform: capitalize;
        color: var(--white-color);
        text-transform: capitalize;
      "
    >
      Are you sure?
    </h2>
    <p
      class="t16"
      style="text-align: center; color: #c3cde0; margin-bottom: 30px"
    >
      You will need to enter your email and <br />
      password again.
    </p>
    <div
      style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px"
    >
      <app-button
        [text]="'Sure'"
        [routerLink]="'/sign-in'"
        [colorScheme]="'secondary'"
      />
      <app-button [text]="'Cancel'" [routerLink]="'/profile'" />
    </div>
  </section>
</main>

// react/spinride/src/screens/SignOut.tsx
import React from 'react';
import {useNavigate} from 'react-router-dom';

import {hooks} from '../hooks';
import {svg} from '../assets/svg';
import {constants} from '../constants';
import bg from '../assets/bg/01.png';
import {components} from '../components';

export const SignOut: React.FC = () => {
  const navigate = useNavigate();
  hooks.useThemeColor('#161e2f');
  hooks.useBodyColor('#161e2f');

  const renderBackground = () => {
    return (
      <img
        src={bg}
        alt='bg'
        style={{
          position: 'fixed',
          width: '100%',
          height: 'auto',
          zIndex: 1,
          maxWidth: 'var(--screen-width)',
          margin: '0 auto',
        }}
      />
    );
  };

  const renderContent = () => {
    return (
      <main
        style={{
          padding: 20,
          zIndex: 2,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          overflowY: 'auto',
          height: '100%',
          paddingBottom: '20%',
        }}
      >
        <div style={{marginBottom: 14}}>
          <svg.SignOutSvg />
        </div>
        <h2
          style={{
            color: 'var(--white-color)',
            textTransform: 'capitalize',
            marginBottom: 14,
          }}
        >
          Are you sure?
        </h2>
        <p
          style={{
            maxWidth: 335,
            textAlign: 'center',
            color: '#C3CDE0',
            marginBottom: 30,
          }}
          className='t16'
        >
          You will need to enter your email and password again.
        </p>
        <div
          style={{
            display: 'grid',
            gap: 15,
            width: '100%',
            gridTemplateColumns: 'repeat(2, 1fr)',
          }}
        >
          <components.Button
            title='Sure'
            colorScheme='secondary'
            onClick={() => navigate(constants.routes.SIGN_IN)}
          />
          <components.Button
            title='Cancel'
            onClick={() => navigate(-1)}
          />
        </div>
      </main>
    );
  };

  return (
    <components.MotionWrapper>
      <components.SafeAreaView>
        {renderBackground()}
        {renderContent()}
      </components.SafeAreaView>
    </components.MotionWrapper>
  );
};
