// angular/spinride/src/app/screens/verify-your-email/verify-your-email.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'app-verify-your-email',
  standalone: false,
  templateUrl: './verify-your-email.component.html',
  styleUrl: './verify-your-email.component.scss',
})
export class VerifyYourEmailComponent {}

<app-header [showGoBack]="true" [title]="'Verify your email'" />

<main class="verify-phone-main">
  <p class="verify-phone-text">
    We have sent you an email with a verification code.
  </p>
  <app-input-field
    [check]="true"
    [value]="'darronbanks@mail.com'"
    [containerStyle]="{'margin-bottom': '14px'}"
  />
  <app-button [text]="'confirm'" [routerLink]="'/verification-email'" />
</main>

// react/spinride/src/screens/VerifyYourEmail.tsx
import React, {useState} from 'react';
import {useNavigate} from 'react-router-dom';

import {constants} from '../constants';
import {components} from '../components';
import styles from '../modules/verify-your-phone-number.module.scss';

export const VerifyYourEmail: React.FC = () => {
  const navigate = useNavigate();

  const [form, setForm] = useState({
    email: 'darronbanks@mail.com',
  });

  const handleChangeField = (field: keyof typeof form, label: string) => {
    const result = window.prompt(`Enter your ${label}`, form[field]);
    if (result !== null) {
      setForm((prev) => ({...prev, [field]: result}));
    }
  };

  const renderHeader = () => {
    return (
      <components.Header
        showGoBack={true}
        title="Verify your email"
        headerStyle={{backgroundColor: 'var(--anti-flash-white)'}}
      />
    );
  };

  const renderContent = () => {
    return (
      <main className={styles.container}>
        <p
          className="t16"
          style={{marginBottom: 30, textAlign: 'center', maxWidth: 335}}
        >
          We have sent you an email with a verification code.
        </p>
        <components.InputField
          className={styles.inputField}
          placeholder="+17 0123456789"
          value={form.email}
          onClick={() => handleChangeField('email', 'email address')}
        />
        <components.Button
          title="Confirm"
          onClick={() => {
            navigate(constants.routes.VERIFICATION, {
              state: {email: form.email},
            });
          }}
        />
      </main>
    );
  };

  return (
    <components.MotionWrapper>
      <components.SafeAreaView>
        {renderHeader()}
        {renderContent()}
      </components.SafeAreaView>
    </components.MotionWrapper>
  );
};
