// react/spinride/src/items/ReviewItem.tsx
import React from 'react';

import type {ReviewType} from '../types';
import {svg} from '../assets/svg';

type Props = {
  review: ReviewType;
};

export const ReviewItem: React.FC<Props> = ({review}) => {
  return (
    <li
      style={{
        backgroundColor: 'var(--white-color)',
        padding: 16,
        borderRadius: 12,
        display: 'flex',
        flexDirection: 'row',
      }}
    >
      <img
        src={review.photo}
        style={{borderRadius: '50%', width: 30, height: 30, marginRight: 10}}
      />
      <div style={{width: '100%'}}>
        <div
          style={{
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            width: '100%',
            marginBottom: 6,
          }}
        >
          <h5>{review.name}</h5>
          <svg.RatingStarsSvg rating={review.rating} />
        </div>
        <span className="t10" style={{marginBottom: 10, display: 'block'}}>
          {review.date}
        </span>
        <p className="t14">{review.comment}</p>
      </div>
    </li>
  );
};

// angular/spinride/src/app/items/review-item/review-item.component.ts
import {Component, Input} from '@angular/core';

import {ReviewModel} from '../../models/review.model';

@Component({
  selector: 'app-review-item',
  standalone: false,
  templateUrl: './review-item.component.html',
  styleUrl: './review-item.component.scss',
})
export class ReviewItemComponent {
  @Input() review: ReviewModel | undefined;
}

<div
  style="
    padding: 20px;
    border-radius: 10px;
    width: 100%;
    background-color: var(--white-color);
  "
>
  <div
    style="
      display: flex;
      flex-direction: row;
      align-items: center;
      width: 100%;
      padding-bottom: 13px;
      border-bottom: 1px solid rgba(0, 0, 0, 0.1);
      margin-bottom: 11px;
    "
  >
    <img
      [src]="review?.avatar"
      style="width: 30px; height: 30px; margin-right: 14px"
    />
    <div style="width: 100%">
      <div
        style="
          display: flex;
          flex-direction: row;
          align-items: center;
          width: 100%;
        "
      >
        <h5 style="margin-right: auto">{{ review?.name }}</h5>
        <span class="t10">{{ review?.date }}</span>
      </div>
      <div
        style="
          display: flex;
          flex-direction: row;
          align-items: center;
          justify-content: space-between;
        "
      >
        <app-stars [rating]="3" />
        <button>
          <span class="t10" style="color: var(--main-turquoise)">Reply</span>
        </button>
      </div>
    </div>
  </div>
  <p class="t14">{{ review?.comment }}</p>
</div>
