// react/spinride/src/screens/PhoneNumberHasBeenVerified.tsx
import React from 'react';
import {useNavigate} from 'react-router-dom';

import {hooks} from '../hooks';
import {svg} from '../assets/svg';
import bg from '../assets/bg/01.png';
import {components} from '../components';

export const PhoneNumberHasBeenVerified: React.FC = () => {
  const navigate = useNavigate();
  hooks.useThemeColor('#161e2f');
  hooks.useBodyColor('#161e2f');

  const renderBackground = () => {
    return (
      <img
        src={bg}
        alt='bg'
        style={{
          position: 'fixed',
          width: '100%',
          height: 'auto',
          zIndex: 1,
          maxWidth: 'var(--screen-width)',
          margin: '0 auto',
        }}
      />
    );
  };

  const renderContent = () => {
    return (
      <main
        style={{
          padding: 20,
          zIndex: 2,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          overflowY: 'auto',
          height: '100%',
          paddingBottom: '20%',
        }}
      >
        <div style={{marginBottom: 14}}>
          <svg.PhoneCallSvg />
        </div>
        <h2
          style={{
            color: 'var(--white-color)',
            textTransform: 'capitalize',
            marginBottom: 14,
            maxWidth: 308,
            textAlign: 'center',
          }}
        >
          Your phone number has been successfully verified!
        </h2>
        <p
          style={{
            maxWidth: 290,
            textAlign: 'center',
            color: '#C3CDE0',
            marginBottom: 30,
          }}
          className='t16'
        >
          Now that your account is fully set up, immerse yourself in the world
          of bikes.
        </p>
        <components.Button
          title='Done'
          onClick={() => navigate(-1)}
          containerStyle={{maxWidth: 170, width: '100%'}}
        />
      </main>
    );
  };

  return (
    <components.MotionWrapper>
      <components.SafeAreaView>
        {renderBackground()}
        {renderContent()}
      </components.SafeAreaView>
    </components.MotionWrapper>
  );
};

// angular/spinride/src/app/screens/phone-number-has-been-verified/phone-number-has-been-verified.component.ts
import {Component, OnInit} from '@angular/core';

import {svg} from '@svg/index';
import {MetaService} from '@services/meta.service';
import {VerificationService} from '@services/verification.service';

@Component({
  selector: 'app-phone-number-has-been-verified',
  standalone: false,
  templateUrl: './phone-number-has-been-verified.component.html',
  styleUrl: './phone-number-has-been-verified.component.scss',
})
export class PhoneNumberHasBeenVerifiedComponent implements OnInit {
  svg = svg;
  constructor(
    private metaService: MetaService,
    private verificationService: VerificationService,
  ) {}

  ngOnInit(): void {
    this.setMeta();
    this.setPhoneVerification();
  }

  setMeta(): void {
    this.metaService.setThemeColor('#161E2F');
    this.metaService.setBackgroundColor('#161E2F');
  }

  setPhoneVerification(): void {
    this.verificationService.setPhoneVerified();
  }
}

<img
  src="./assets/bg/01.png"
  alt="Add to cart"
  style="position: absolute; width: 100%; height: auto; z-index: -1"
/>

<main
  style="
    height: 100%;
    overflow-y: auto;
    margin-left: 20px;
    margin-right: 20px;
    -webkit-overflow-scrolling: touch;
    scroll-behavior: smooth;
    user-select: none;
  "
>
  <section
    style="
      height: 100%;
      display: flex;
      justify-content: center;
      flex-direction: column;
      padding-bottom: 20%;
    "
  >
    <img
      [alt]="'phone number verified'"
      [src]="svg.phoneCall"
      style="width: 180px; margin: 0 auto; margin-bottom: 20px"
    />
    <h2
      style="
        text-align: center;
        margin-bottom: 14px;
        text-transform: capitalize;
        color: var(--white-color);
        text-transform: capitalize;
      "
    >
      Your phone number has <br />
      been successfully verified!
    </h2>
    <p
      class="t16"
      style="text-align: center; color: #c3cde0; margin-bottom: 30px"
    >
      You can now use the app <br />
      and enjoy all the features.
    </p>
    <div style="max-width: 170px; margin: 0 auto; width: 100%">
      <app-button [text]="'done'" [routerLink]="'/profile'" />
    </div>
  </section>
</main>
