// react/spinride/src/screens/WishlistEmpty.tsx
import React from 'react';

import {hooks} from '../hooks';
import {svg} from '../assets/svg';
import {constants} from '../constants';
import {components} from '../components';

export const WishlistEmpty: React.FC = () => {
  hooks.useThemeColor('#161e2f');
  hooks.useBodyColor('#161e2f');

  const {navigate} = hooks.useRouter();

  const renderBackground = () => {
    return (
      <img
        src={constants.images.bg01}
        alt="bg"
        style={{
          position: 'fixed',
          width: '100%',
          height: 'auto',
          zIndex: 1,
          maxWidth: 'var(--screen-width)',
          margin: '0 auto',
        }}
      />
    );
  };

  const renderContent = () => {
    return (
      <main
        style={{
          paddingLeft: 20,
          paddingRight: 20,
          zIndex: 2,
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          overflowY: 'auto',
          height: '100%',
          paddingBottom: 'calc(var(--bottom-tabbar-height) + 40px)',
        }}
      >
        <div style={{marginBottom: 14}}>
          <svg.EmptyHeartSvg />
        </div>
        <h2
          style={{
            color: 'var(--white-color)',
            textTransform: 'capitalize',
            marginBottom: 14,
            textAlign: 'center',
          }}
        >
          Your Wishlist is empty!
        </h2>
        <p
          style={{
            maxWidth: 283,
            textAlign: 'center',
            color: '#C3CDE0',
            marginBottom: 30,
          }}
          className="t16"
        >
          Looks like you haven't chosen the items you like.
        </p>
        <components.Button
          title="shop now"
          onClick={() => navigate(constants.routes.HOME)}
          containerStyle={{maxWidth: 170, width: '100%'}}
        />
      </main>
    );
  };

  const renderBottomBar = () => {
    return (
      <components.BottomTabBar
        containerStyle={{
          backgroundColor: 'transparent',
        }}
        tabsContainerStyle={{
          border: '1px solid #555C6A',
        }}
      />
    );
  };

  return (
    <components.MotionWrapper>
      <components.SafeAreaView>
        {renderBackground()}
        {renderContent()}
        {renderBottomBar()}
      </components.SafeAreaView>
    </components.MotionWrapper>
  );
};

// angular/spinride/src/app/screens/wishlist-empty/wishlist-empty.component.ts
import {Component, OnInit} from '@angular/core';

import {svg} from '../../../../public/assets/svg';
import {MetaService} from '../../services/meta.service';

@Component({
  selector: 'app-wishlist-empty',
  standalone: false,
  templateUrl: './wishlist-empty.component.html',
  styleUrl: './wishlist-empty.component.scss',
})
export class WishlistEmptyComponent implements OnInit {
  public svg = svg;

  constructor(private metaService: MetaService) {}

  ngOnInit(): void {
    this.metaService.setThemeColor('#161E2F');
    this.metaService.setBackgroundColor('#161E2F');
  }
}

<img
  src="./assets/bg/01.png"
  alt="Add to cart"
  style="position: absolute; width: 100%; height: auto; z-index: -1"
/>

<main
  style="height: 100%; overflow-y: auto; margin-left: 20px; margin-right: 20px"
>
  <section
    style="
      height: 100%;
      display: flex;
      justify-content: center;
      flex-direction: column;
    "
  >
    <img
      [alt]="'info saved'"
      [src]="svg.emptyHeart"
      style="width: 180px; margin: 0 auto; margin-bottom: 20px"
    />
    <h2
      style="
        text-align: center;
        margin-bottom: 14px;
        text-transform: capitalize;
        color: var(--white-color);
        text-transform: capitalize;
      "
    >
      Your Wishlist is empty!
    </h2>
    <p
      class="t16"
      style="text-align: center; color: #c3cde0; margin-bottom: 30px"
    >
      Looks like you haven't chosen the <br />
      items you like.
    </p>
    <div style="max-width: 170px; margin: 0 auto; width: 100%">
      <app-button [text]="'shop now'" [routerLink]="'/shop'" />
    </div>
  </section>
</main>

<app-bottom-tab-bar
  [style]="{backgroundColor: 'transparent', paddingTop: '0px'}"
  [footerStyle]="{border: '1px solid #555C6A'}"
/>
