// angular/spinride/src/app/components/button/button.component.ts
import {Component, Input} from '@angular/core';

@Component({
  selector: 'app-button',
  templateUrl: './button.component.html',
  styleUrl: './button.component.scss',
  standalone: false,
})
export class ButtonComponent {
  @Input() text: string = '';
  @Input() routerLink: string | string[] | undefined;
  @Input() onClick!: () => void;
  @Input() colorScheme: 'primary' | 'secondary' = 'primary';
  @Input() containerStyle: {[key: string]: string} = {};

  linkStyles(): {[key: string]: string} {
    return {
      'background-color':
        this.colorScheme === 'primary'
          ? 'var(--main-orange)'
          : 'var(--white-color)',

      display: 'flex',
      'align-items': 'center',
      'justify-content': 'center',
      width: '100%',
      height: '50px',
      'border-radius': '50px',
      ...this.containerStyle,
    };
  }

  textStyles(): {[key: string]: string} {
    return {
      fontFamily: 'Mulish',
      fontSize: '16px',
      fontWeight: '600',
      textTransform: 'capitalize',
      color: this.colorScheme === 'primary' ? '#fff' : 'var(--main-color)',
    };
  }
}

<a [routerLink]="routerLink" class="t16" [ngStyle]="linkStyles()">
  <span class="t14" [ngStyle]="textStyles()">
    {{ text }}
  </span>
</a>

// react/spinride/src/components/Button.tsx
import React from 'react';

interface ButtonProps {
  title: string;
  onClick?: () => void;
  colorScheme?: 'primary' | 'secondary';
  containerStyle?: React.CSSProperties;
}

export const Button: React.FC<ButtonProps> = ({
  title,
  onClick,
  colorScheme = 'primary',
  containerStyle,
}) => {
  return (
    <div style={containerStyle}>
      <button
        onClick={onClick}
        style={{
          width: '100%',
          height: 50,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          borderRadius: 50,
          border: 'none',
          background:
            colorScheme === 'primary'
              ? 'var(--main-orange-color)'
              : 'var(--white-color)',
        }}
      >
        <span
          style={{
            fontWeight: 600,
            textTransform: 'capitalize',
            fontSize: 16,
            color:
              colorScheme === 'primary'
                ? 'var(--white-color)'
                : 'var(--main-dark-color)',
          }}
        >
          {title}
        </span>
      </button>
    </div>
  );
};
