// angular/spinride/src/app/components/header/header.component.ts
import {Observable} from 'rxjs';
import {Location} from '@angular/common';
import {isMobile} from 'react-device-detect';
import {Component, Input, OnInit} from '@angular/core';

import {URLS} from '../../config';
import {svg} from '../../../../public/assets/svg';
import {CartState} from '../../services/cart.service';
import {CartService} from '../../services/cart.service';
import {ModalService} from '../../services/modal.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss',
  standalone: false,
})
export class HeaderComponent implements OnInit {
  svg = svg;
  URLS = URLS;
  @Input() title: string = '';
  @Input() showUser: Boolean = false;
  @Input() showLogo: Boolean = false;
  @Input() showSearch: Boolean = false;
  @Input() showBasket: Boolean = false;
  @Input() showGoBack: Boolean = false;
  @Input() showBurger: Boolean = false;
  @Input() showBorder: Boolean = false;
  @Input() showUserName: Boolean = false;
  @Input() headerStyle: {[key: string]: string} = {};

  cartState$: Observable<CartState>;

  isMobile = isMobile;
  total: number = 0;

  constructor(
    private cartService: CartService,
    private location: Location,
    private modalService: ModalService,
  ) {
    this.cartState$ = this.cartService.cartState$;
  }

  openModal(): void {
    this.modalService.openModal();
  }

  closeModal(): void {
    this.modalService.closeModal();
  }

  toggleModal(): void {
    this.modalService.toggleModal();
  }

  goBack(): void {
    this.location.back();
  }

  ngOnInit(): void {
    this.cartState$.subscribe(state => {
      this.total = state.total;
    });
  }

  get combinedStyles(): {[key: string]: string} {
    return {
      ...this.headerStyle,
      'max-width': this.isMobile ? '100%' : 'var(--screen-width)',
      'border-bottom': this.showBorder ? '1px solid #E2E2E2' : 'none',
    };
  }
}

<header
  [ngStyle]="combinedStyles"
  style="
    width: 100%;
    z-index: 8;
    display: flex;
    align-items: center;
    flex-direction: row;
    height: var(--header-height);
    justify-content: space-between;
    /* border: 1px solid red; */
  "
>
  <!-- GO BACK -->
  <button
    (click)="goBack()"
    *ngIf="showGoBack"
    style="
      padding-left: 20px;
      padding-right: 20px;
      height: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
    "
  >
    <img src="assets/svg/go-back.svg" alt="go back icon" />
  </button>

  <!-- BURGER -->
  <button>
    <img
      *ngIf="showBurger"
      [src]="svg.burger"
      alt="burger icon"
      style="
        padding-left: 20px;
        padding-right: 20px;
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
      "
    />
  </button>

  <!-- TITLE -->
  <h4
    *ngIf="title"
    style="
      position: absolute;
      left: 50%;
      transform: translateX(-50%);
      text-align: center;
      color: var(--main-color);
    "
  >
    {{ title }}
  </h4>

  <!-- SEARCH -->
  <button
    *ngIf="showSearch"
    style="position: absolute; right: 50%; transform: translateX(50%)"
  >
    <img [src]="svg.headerSearch" alt="logo" />
  </button>

  <!-- BASKET -->
  <a
    *ngIf="showBasket"
    [routerLink]="['/order']"
    style="
      display: flex;
      padding: 0 20px;
      position: absolute;
      right: 0;
      align-items: center;
      justify-content: center;
      height: var(--header-height);
      position: absolute;
    "
  >
    <div
      style="
        /* height: 20px; */
        border-radius: 30px;
        padding: 5px 4px 3px 4px;
        display: flex;
        align-items: center;
        justify-content: center;
        position: absolute;
        right: 34px;
        bottom: 8px;
        background-color: var(--main-orange);
        display: flex;
        justify-content: center;
        align-items: center;
      "
    >
      <span
        style="
          font-size: 10px;
          font-weight: 400;
          display: block;
          margin-bottom: 2px;
          line-height: 1;
          color: var(--white-color);
          font-weight: 700;
          font-family: var(--mulish);
        "
      >
        ${{
          total.toFixed(2) === '0.00'
            ? '0'
            : total.toFixed(2) === '-0.00'
            ? '0'
            : total.toFixed(2)
        }}
      </span>
    </div>
    <img alt="basket" src="assets/svg/basket.svg" />
  </a>
</header>

// react/spinride/src/components/Header.tsx
import React from 'react';
import {useAtomValue} from 'jotai';

import {hooks} from '../hooks';
import {svg} from '../assets/svg';
import {constants} from '../constants';
import {cartAtom} from '../atoms/cart.atom';

type Props = {
  title?: string;
  showGoBack?: boolean;
  showUser?: boolean;
  showBurger?: boolean;
  showBasket?: boolean;
  headerStyle?: React.CSSProperties;
  showBorder?: boolean;
};

export const Header: React.FC<Props> = ({
  title,
  showGoBack,
  showBurger,
  showBasket,
  showBorder,
}) => {
  const {navigate} = hooks.useRouter();
  const cart = useAtomValue(cartAtom);

  const canGoBack = showGoBack && window.history.length > 1;

  const renderGoBack = () => {
    if (!showGoBack && !canGoBack) return null;

    return (
      <button
        style={{paddingLeft: 20, paddingRight: 20}}
        onClick={() => {
          navigate(-1);
        }}
      >
        <svg.GoBackSvg />
      </button>
    );
  };

  const renderBurgerMenu = () => {
    if (!showBurger) return null;

    return (
      <button style={{paddingLeft: 20, paddingRight: 20}}>
        <svg.BurgerSvg />
      </button>
    );
  };

  const renderBasket = () => {
    if (!showBasket) return null;
    return (
      <button
        style={{paddingLeft: 20, paddingRight: 20}}
        onClick={() => {
          navigate(constants.routes.ORDER);
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            position: 'relative',
          }}
        >
          <svg.BagSvg />
        </div>
        <div
          style={{
            height: 19,
            backgroundColor: 'var(--main-orange-color)',
            borderRadius: 10,
            paddingLeft: 4,
            paddingRight: 4,
            position: 'absolute',
            bottom: 7,
            right: 34,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <span
            style={{
              fontSize: 10,
              color: 'var(--white-color)',
              fontWeight: 700,
            }}
          >
            ${cart.total ? cart.total.toFixed(2) : '0'}
          </span>
        </div>
      </button>
    );
  };

  const renderTitle = () => {
    return (
      <div
        style={{
          position: 'absolute',
          left: '50%',
          transform: 'translateX(-50%)',
        }}
      >
        <h4>{title}</h4>
      </div>
    );
  };

  return (
    <header
      style={{
        display: 'flex',
        position: 'fixed',
        top: 0,
        left: '50%',
        transform: 'translateX(-50%)',
        width: '100%',
        zIndex: 1000,
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#F3F3F3',

        // backgroundColor: 'red',
        height: 'var(--header-height)',
        maxWidth: 'var(--screen-width)',
        borderBottom: showBorder
          ? '1px solid #E2E2E2'
          : '1px solid transparent',
        margin: '0 auto',
      }}
    >
      {renderGoBack()}
      {renderTitle()}
      {renderBurgerMenu()}
      {renderBasket()}
    </header>
  );
};
