// angular/spinride/src/app/components/home-carousel/home-carousel.component.ts
import {Component, Input} from '@angular/core';

@Component({
  selector: 'app-home-carousel',
  standalone: false,
  templateUrl: './home-carousel.component.html',
  styleUrl: './home-carousel.component.scss',
})
export class HomeCarouselComponent {
  @Input() slides: any[] = [];
}

<!-- CAROUSEL -->
<section style="position: relative; margin-bottom: 30px">
  <!-- images -->
  <owl-carousel-o
    [options]="customOptions"
    (translated)="onSlideChange($event)"
  >
    <ng-template
      carouselSlide
      *ngFor="let item of carousel; let i = index"
      class="item"
    >
      <a [routerLink]="['/bicycle', '1']">
        <img [src]="item.banner" style="width: 100%; margin: 0 auto" />
      </a>
    </ng-template>
  </owl-carousel-o>

  <!-- dots -->
  <section
    style="
      display: flex;
      justify-content: center;
      position: absolute;
      bottom: 0;
      z-index: 1;
      left: 50%;
      transform: translateX(-50%);
      margin-bottom: 20px;
    "
  >
    <ul
      style="display: flex; gap: 8px; flex-direction: row; align-items: center"
    >
      <li
        *ngFor="let item of carousel; let i = index"
        [className]="i === 0 ? 'active' : ''"
        style="
          display: inline-block;
          cursor: pointer;
          background-color: #000;
          border-radius: 10px;
        "
        [ngStyle]="{
        width: '8px',
        height: activeSlide === i ? '20px' : '8px',
        backgroundColor: i === activeSlide ? 'var(--white-color)' : 'rgba(255, 255, 255, 0.5)',
      }"
      ></li>
    </ul>
  </section>
</section>

// react/spinride/src/components/HomeCarousel.tsx
import 'swiper/swiper-bundle.css';
import React, {useState} from 'react';
import {Swiper, SwiperSlide} from 'swiper/react';

import {hooks} from '../hooks';
import {constants} from '../constants';
import type {CarouselType} from '../types';

type Props = {
  bikeId?: number;
  carousel: CarouselType[];
};

export const HomeCarousel: React.FC<Props> = ({carousel, bikeId}) => {
  const images = carousel.map((item) => item.image);
  const [activeIndex, setActiveIndex] = useState(0);

  const {navigate} = hooks.useRouter();

  const renderContent = () => {
    return (
      <section style={{position: 'relative', marginBottom: 40}}>
        {/* CAROUSEL */}
        <Swiper onSlideChange={(swiper) => setActiveIndex(swiper.activeIndex)}>
          {images.map((image, index) => {
            return (
              <SwiperSlide
                style={{
                  width: '100%',
                  paddingLeft: 20,
                  paddingRight: 20,
                  borderRadius: 12,
                }}
                key={index}
              >
                <button
                  style={{
                    height: '100%',
                    width: '100%',
                    borderRadius: 12,
                    overflow: 'hidden',
                  }}
                  onClick={() => {
                    if (bikeId) {
                      navigate(constants.routes.BIKE, {state: {bikeId}});
                    } else {
                      navigate(constants.routes.SHOP);
                    }
                  }}
                >
                  <img
                    src={image}
                    alt={`Bike image ${index + 1}`}
                    style={{
                      width: '100%',
                      objectFit: 'cover',
                      borderRadius: 12,
                      overflow: 'hidden',
                      height: '100%',
                    }}
                  />
                </button>
              </SwiperSlide>
            );
          })}
        </Swiper>
        {/* DOTS */}
        <ul
          style={{
            position: 'absolute',
            zIndex: 1,
            display: 'flex',
            flexDirection: 'row',
            bottom: 20,
            left: '50%',
            transform: 'translateX(-50%)',
            gap: 4,
          }}
        >
          {images.map((image, index) => {
            return (
              <li
                key={index}
                style={{
                  width: 6,
                  height: 6,
                  borderRadius: '50%',
                  backgroundColor:
                    activeIndex === index
                      ? 'var(--white-color)'
                      : 'rgba(255, 255, 255, 0.5)',
                }}
              />
            );
          })}
        </ul>
      </section>
    );
  };

  return renderContent();
};
