// angular/spinride/src/app/components/loader/loader.component.ts
import {Component, Input} from '@angular/core';

@Component({
  selector: 'app-loader',
  templateUrl: './loader.component.html',
  styleUrl: './loader.component.scss',
  standalone: false,
})
export class LoaderComponent {
  @Input() containerStyle: {[key: string]: string} = {};
}

<div
  style="
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: #f5fafb;
    position: fixed;
    inset: 0;
    bottom: 0;
  "
  [ngStyle]="containerStyle"
>
  <div
    style="
      border: 4px solid rgba(0, 0, 0, 0.1);
      border-top: 4px solid #6c6d84;
      border-radius: 50%;
      width: 40px;
      height: 40px;
      animation: spin 1s linear infinite;
    "
  ></div>
</div>

// react/spinride/src/components/Loader.tsx
export const Loader: React.FC = () => {
  return (
    <div
      style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        height: '100%',
        position: 'absolute',
        top: 0,
        left: 0,
      }}
    >
      <span
        style={{
          width: 32,
          height: 32,
          border: '2px solid #FF8A71',
          borderRadius: '50%',
          display: 'inline-block',
          animation: 'spin 1s linear infinite',
        }}
      />
      <style>{`
                @keyframes spin {
                  0% { transform: rotate(0deg); }
                  100% { transform: rotate(360deg); }
                }
              `}</style>
    </div>
  );
};
