// react/spinride/src/screens/SignIn.tsx
import React, {useState} from 'react';
import {Link} from 'react-router-dom';

import {hooks} from '../hooks';
import {svg} from '../assets/svg';
import {constants} from '../constants';
import {components} from '../components';

export const SignIn: React.FC = () => {
  const {navigate} = hooks.useRouter();
  const [isRememberMe, setIsRememberMe] = useState(false);

  hooks.useThemeColor('#F3F3F3');
  hooks.useBodyColor('#F3F3F3');

  const [form, setForm] = useState({
    email: '',
    password: '',
  });

  const handleChangeField = (field: keyof typeof form, label: string) => {
    const result = window.prompt(`Enter your ${label}`, form[field]);
    if (result !== null) {
      setForm((prev) => ({...prev, [field]: result}));
    }
  };

  const renderHeader = () => {
    return (
      <components.Header
        showGoBack={true}
        title="Sign In"
        headerStyle={{backgroundColor: 'var(--anti-flash-white)'}}
      />
    );
  };

  const renderContent = () => {
    return (
      <main
        style={{
          overflowY: 'auto',
          paddingTop: 'calc(var(--header-height) + 20px)',
          paddingBottom: 20,
          paddingLeft: 20,
          paddingRight: 20,
          display: 'flex',
          flexDirection: 'column',
          height: '100%',
          justifyContent: 'center',
        }}
      >
        <h1 style={{textAlign: 'center', marginBottom: 14}}>Welcome Back!</h1>
        <p
          style={{
            marginBottom: 30,
            textAlign: 'center',
            color: 'var(--text-color)',
          }}
        >
          Sign in to continue
        </p>
        <components.InputField
          placeholder="cristinawolf@mail.com"
          value={form.email}
          onClick={() => handleChangeField('email', 'email')}
          isValid={form.email.length > 0 && form.email.includes('@')}
          containerStyle={{marginBottom: 14}}
        />
        <components.InputField
          placeholder="••••••"
          inputType="password"
          value={form.password}
          onClick={() => handleChangeField('password', 'password')}
          containerStyle={{marginBottom: 20}}
        />
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginBottom: 24,
          }}
        >
          <div
            onClick={() => setIsRememberMe(!isRememberMe)}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 12,
              cursor: 'pointer',
            }}
          >
            <div
              style={{
                width: 18,
                height: 18,
                backgroundColor: 'var(--white-color)',
                borderRadius: 5,
                border: '1px solid #EEEEEE',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              {isRememberMe && <svg.CheckSvg />}
            </div>
            <span className="t16" style={{lineHeight: 1, marginBottom: 1}}>
              Remember me
            </span>
          </div>

          <Link to={constants.routes.FORGOT_PASSWORD}>Forgot password?</Link>
        </div>

        <components.Button
          title="Sign In"
          containerStyle={{marginBottom: 20}}
          onClick={() => {
            navigate(constants.routes.HOME, {
              replace: true,
            });
          }}
        />
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 4,
          }}
        >
          <span className="t16">Don’t have an account? </span>
          <Link to={constants.routes.SIGN_UP}>Sign up.</Link>
        </div>
      </main>
    );
  };

  return (
    <components.MotionWrapper>
      <components.SafeAreaView>
        {renderHeader()}
        {renderContent()}
      </components.SafeAreaView>
    </components.MotionWrapper>
  );
};

// angular/spinride/src/app/screens/sign-in/sign-in.component.ts
import {Component} from '@angular/core';

import {svg} from '../../../../public/assets/svg';
import {MetaService} from '../../services/meta.service';

@Component({
  selector: 'app-sign-in',
  templateUrl: './sign-in.component.html',
  styleUrl: './sign-in.component.scss',
  standalone: false,
})
export class SignInComponent {
  svg = svg;
  rememberMe = false;

  constructor(private metaService: MetaService) {}

  ngOnInit(): void {
    this.metaService.setThemeColor('#F3F3F3');
    this.metaService.setBackgroundColor('#F3F3F3');
  }

  setRememberMe(): void {
    this.rememberMe = !this.rememberMe;
  }
}

<app-header [showGoBack]="true" [title]="'Sign in'" />

<main
  style="
    margin-left: 20px;
    margin-right: 20px;
    overflow-y: auto;
    height: 100%;
    margin-top: 10px;
  "
>
  <section
    style="
      height: 100%;
      display: flex;
      justify-content: center;
      flex-direction: column;
    "
  >
    <h1 style="margin-bottom: 14px; text-align: center">Welcome Back!</h1>
    <span
      style="
        margin-bottom: 30px;
        text-align: center;
        font-family: var(--mulish);
        font-weight: 400;
        color: var(--text-color);
        font-size: 16px;
        line-height: 1.7;
      "
    >
      Sign in to continue
    </span>
    <app-input-field
      [check]="true"
      [type]="'email'"
      [value]="'darronbanks@mail.com'"
      [placeholder]="'dominicparker@mail.com'"
      [ngStyle]="{'margin-bottom': '14px'}"
    />
    <app-input-field
      [placeholder]="'••••••••'"
      [type]="'password'"
      [eyeOff]="true"
      [value]="'••••••••'"
      [ngStyle]="{'margin-bottom': '16px'}"
    />
    <div
      style="
        margin-bottom: 32px;
        display: flex;
        flex-direction: row;
        justify-content: space-between;
      "
    >
      <div
        style="
          display: flex;
          flex-direction: row;
          gap: 10px;
          align-items: center;
          cursor: pointer;
        "
        (click)="rememberMe = !rememberMe"
      >
        <div
          style="
            width: 18px;
            height: 18px;
            background-color: var(--white-color);
            border-radius: 5px;
            background-color: #fff;
            display: flex;
            justify-content: center;
            align-items: center;
            border: 1px solid #eeeeee;
          "
        >
          <img
            [src]="svg.check"
            alt=""
            style="width: 10px"
            *ngIf="rememberMe"
          />
        </div>
        <span
          style="
            font-size: 16;
            font-weight: 400;
            font-family: var(--mulish);
            color: var(--text-color);
          "
        >
          Remember me
        </span>
      </div>

      <a href="" [routerLink]="'/forgot-password'">
        <span
          style="
            font-size: 16;
            font-family: var(--mulish);
            font-weight: 400;
            color: var(--main-color);
          "
        >
          Forgot password?
        </span>
      </a>
    </div>
    <app-button
      [text]="'Sign in'"
      [routerLink]="'/home'"
      [ngStyle]="{'margin-bottom': '20px'}"
    />

    <div
      style="display: flex; flex-direction: row; gap: 5px; align-self: center"
    >
      <span
        style="
          font-family: var(--mulish);
          font-size: 16;
          color: var(--text-color);
        "
      >
        Don’t have an account?
      </span>
      <a
        [routerLink]="'/sign-up'"
        style="
          font-family: var(--mulish);
          font-size: 16;
          color: var(--main-color);
        "
      >
        Sign up.
      </a>
    </div>
  </section>
</main>
