// angular/spinride/src/app/items/promocode-item/promocode-item.component.ts
import {Component, Input, Output, EventEmitter} from '@angular/core';

import {svg} from '@svg/index';
import {Promocode} from '../../models/promocode.model';

@Component({
  selector: 'app-promocode-item',
  templateUrl: './promocode-item.component.html',
  styleUrl: './promocode-item.component.scss',
  standalone: false,
})
export class PromocodeItemComponent {
  @Input() promocode?: Promocode;
  @Output() copied = new EventEmitter<string>();

  svg = svg;

  copyToClipboard(text: string): void {
    navigator.clipboard.writeText(text).then(
      () => {
        alert(`${text} code copied to clipboard`);
      },
      err => {
        console.error('Could not copy text: ', err);
      },
    );
  }
}

<li
  *ngIf="promocode"
  style="
    background-color: var(--white-color);
    border-radius: 12px;
    width: 100%;
    padding: 10px;
    display: flex;
    flex-direction: row;
    align-items: center;
    gap: 17px;
    position: relative;
  "
  (click)="
    $event.stopPropagation();
    $event.preventDefault();
    copyToClipboard(promocode.code || '')
  "
>
  <img
    [src]="promocode.image"
    alt="promocode"
    style="width: 80px; height: 90px; border-radius: 12px"
  />
  <div style="display: flex; flex-direction: column">
    <h5 style="margin-bottom: 3px">{{ promocode.code }}</h5>
    <span
      style="font-family: var(--mulish); font-weight: 600; font-size: 16px"
      [ngStyle]="{
        color:
          promocode.discount >= 50
            ? '#FF4365'
            : promocode.discount >= 30
            ? '#FF7557'
            : '#51BA74'
      }"
      >{{ promocode.discount }}% off
    </span>
    <span class="t14" style="margin-top: 3px">{{ promocode.expires_at }}</span>
  </div>
  <div style="padding: 20px; position: absolute; right: 0; top: 0">
    <img [src]="svg.copy" />
  </div>
</li>

// react/spinride/src/items/PromocodeItem.tsx
import React, {useState} from 'react';

import {svg} from '../assets/svg';
import {components} from '../components';
import type {PromocodeType} from '../types';

type Props = {
  promocode: PromocodeType;
};

export const PromocodeItem: React.FC<Props> = ({promocode}) => {
  const [visible, setVisible] = useState(false);
  const [message, setMessage] = useState<string>('');

  const color = () => {
    if (promocode.discount <= 15) {
      return '#51BA74';
    }
    if (promocode.discount <= 30) {
      return '#FF7557';
    }

    if (promocode.discount >= 50) {
      return '#FF4365';
    }
  };

  const renderFlashMessage = () => {
    return (
      <components.FlashMessage
        type={'error'}
        visible={visible}
        setVisible={setVisible}
        message={message}
      />
    );
  };

  const renderContent = () => {
    return (
      <button
        style={{
          backgroundColor: 'var(--white-color)',
          width: '100%',
          borderRadius: 12,
          padding: 10,
          display: 'flex',
          flexDirection: 'row',
          alignItems: 'center',
          gap: 14,
          position: 'relative',
        }}
        onClick={() => {
          setVisible(true);
          setMessage(`"${promocode.code}" has been copied to clipboard.`);
          navigator.clipboard.writeText(promocode.code);
        }}
      >
        <img
          src={promocode.image}
          alt={promocode.code}
          style={{width: 80, height: 90, borderRadius: 12, objectFit: 'cover'}}
        />
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            marginRight: 60,
          }}
        >
          <h5 className="number-of-lines-1">{promocode.code}</h5>
          <span
            style={{
              color: color(),
              fontWeight: 600,
              marginBottom: 3,
            }}
            className="number-of-lines-1"
          >
            {promocode.discount}% off
          </span>
          <span className="t14">{promocode.expires_at}</span>
        </div>
        <div style={{position: 'absolute', right: 20, top: 20}}>
          <svg.CopySvg />
        </div>
      </button>
    );
  };

  return (
    <li style={{width: '100%'}}>
      {renderFlashMessage()}
      {renderContent()}
    </li>
  );
};
