// react/spinride/src/screens/Filter.tsx
import React, {useState} from 'react';

import {hooks} from '../hooks';
import {svg} from '../assets/svg';
import {components} from '../components';

export const Filter: React.FC = () => {
  const {navigate} = hooks.useRouter();

  const bikeTypes = [
    'Road Bikes',
    'Electric Bikes',
    'Hybrid Bikes',
    'Mountain Bikes',
    'Specialty Bikes',
  ];

  const suspensionTypes = [
    'No Suspension',
    'Front Suspension',
    'Full Suspension',
  ];

  const drivetrainOptions = [
    'Single-speed',
    'Electronic shifting',
    'Multiple gears',
  ];

  const tags = [
    {
      key: 'sale',
      label: 'SALE',
      color: '#66A97D',
      checked: true,
    },
    {
      key: 'new',
      label: 'NEW',
      color: '#FF7557',
      checked: false,
    },
    {
      key: 'top',
      label: 'TOP',
      color: '#FF6262',
      checked: false,
    },
  ];

  const colors = [
    {id: 1, code: '#FF6262', name: 'Pastel Red'},
    {id: 2, code: '#63C7FF', name: 'Maya Blue'},
    {id: 3, code: '#F8E7CD', name: 'Champagne'},
    {id: 4, code: '#161E2F', name: 'Eigengrau'},
    {id: 5, code: '#000000', name: 'Black'},
  ];

  const [selectedTags, setSelectedTags] = useState<string[]>([]);
  const [selectedColors, setSelectedColors] = useState<string[]>([]);
  const [selectedBikeTypes, setSelectedBikeTypes] = useState<string[]>([]);
  const [selectedSuspensionTypes, setSelectedSuspensionTypes] = useState<
    string[]
  >([]);
  const [selectedDrivetrainOptions, setSelectedDrivetrainOptions] = useState<
    string[]
  >([]);

  const handleTagChange = (tag: string) => {
    setSelectedTags((prev) =>
      prev.includes(tag) ? prev.filter((t) => t !== tag) : [...prev, tag],
    );
  };
  const handleColorChange = (color: string) => {
    setSelectedColors((prev) =>
      prev.includes(color) ? prev.filter((c) => c !== color) : [...prev, color],
    );
  };
  const handleBikeTypeChange = (type: string) => {
    setSelectedBikeTypes((prev) =>
      prev.includes(type) ? prev.filter((t) => t !== type) : [...prev, type],
    );
  };
  const handleSuspensionTypeChange = (type: string) => {
    setSelectedSuspensionTypes((prev) =>
      prev.includes(type) ? prev.filter((t) => t !== type) : [...prev, type],
    );
  };
  const handleDrivetrainOptionChange = (option: string) => {
    setSelectedDrivetrainOptions((prev) =>
      prev.includes(option)
        ? prev.filter((o) => o !== option)
        : [...prev, option],
    );
  };

  const renderHeader = () => {
    return <components.Header showGoBack={true} title="Filter" />;
  };

  const renderTags = () => {
    return (
      <section style={{paddingLeft: 20, paddingRight: 20, marginBottom: 30}}>
        <ul
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(3, 1fr)',
            gap: 10,
          }}
        >
          {tags.map((tag) => {
            return (
              <li key={tag.key}>
                <button
                  style={{display: 'flex', alignItems: 'center', gap: 8}}
                  onClick={() => handleTagChange(tag.key)}
                >
                  <div
                    style={{
                      width: 18,
                      height: 18,
                      border: '1px solid #EEEEEE',
                      backgroundColor: 'var(--white-color)',
                      borderRadius: 5,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                    }}
                  >
                    {selectedTags.includes(tag.key) && <svg.CheckElementSvg />}
                  </div>
                  <div
                    style={{
                      backgroundColor: tag.color,
                      height: 18,
                      paddingLeft: 6,
                      paddingRight: 6,
                      display: 'flex',
                      alignItems: 'center',
                      borderRadius: 6,
                    }}
                  >
                    <span
                      className="t10"
                      style={{
                        color: 'var(--white-color)',
                        fontWeight: 700,
                        lineHeight: 1.2,
                      }}
                    >
                      {tag.label}
                    </span>
                  </div>
                </button>
              </li>
            );
          })}
        </ul>
      </section>
    );
  };

  const renderColors = () => {
    return (
      <section style={{paddingLeft: 20, paddingRight: 20, marginBottom: 30}}>
        <h5 style={{marginBottom: 14}}>Color</h5>
        <ul
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            alignItems: 'center',
            gap: 14,
          }}
        >
          {colors.map((color) => {
            return (
              <li key={color.id}>
                <button
                  style={{
                    width: 30,
                    height: 30,
                    borderRadius: 15,
                    backgroundColor: color.code,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                  }}
                  onClick={() => handleColorChange(color.code)}
                >
                  {selectedColors.includes(color.code) && <svg.ColorCheckSvg />}
                </button>
              </li>
            );
          })}
        </ul>
      </section>
    );
  };

  const renderBikeTypes = () => {
    return (
      <section style={{paddingLeft: 20, paddingRight: 20, marginBottom: 30}}>
        <h5 style={{marginBottom: 14}}>Bike Type</h5>
        <ul
          style={{
            display: 'flex',
            flexDirection: 'row',
            gap: 8,
            flexWrap: 'wrap',
          }}
        >
          {bikeTypes.map((type) => {
            return (
              <li key={type}>
                <button
                  style={{
                    height: 27,
                    paddingLeft: 20,
                    paddingRight: 20,
                    borderRadius: 30,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    border: selectedBikeTypes.includes(type)
                      ? '1px solid var(--main-orange-color)'
                      : '1px solid #EEEEEE',
                    backgroundColor: selectedBikeTypes.includes(type)
                      ? 'var(--main-orange-color)'
                      : 'var(--white-color)',
                  }}
                  onClick={() => handleBikeTypeChange(type)}
                >
                  <span
                    className="t12"
                    style={{
                      fontWeight: 700,
                      color: selectedBikeTypes.includes(type)
                        ? 'var(--white-color)'
                        : 'var(--main-color)',
                    }}
                  >
                    {type}
                  </span>
                </button>
              </li>
            );
          })}
        </ul>
      </section>
    );
  };

  const renderSuspensionTypes = () => {
    return (
      <section style={{paddingLeft: 20, paddingRight: 20, marginBottom: 30}}>
        <h5 style={{marginBottom: 14}}>Suspension Type</h5>
        <ul
          style={{
            display: 'flex',
            flexDirection: 'row',
            gap: 8,
            flexWrap: 'wrap',
          }}
        >
          {suspensionTypes.map((type) => {
            return (
              <li key={type}>
                <button
                  style={{
                    height: 27,
                    paddingLeft: 20,
                    paddingRight: 20,
                    borderRadius: 30,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    border: selectedSuspensionTypes.includes(type)
                      ? '1px solid var(--main-orange-color)'
                      : '1px solid #EEEEEE',
                    backgroundColor: selectedSuspensionTypes.includes(type)
                      ? 'var(--main-orange-color)'
                      : 'var(--white-color)',
                  }}
                  onClick={() => handleSuspensionTypeChange(type)}
                >
                  <span
                    className="t12"
                    style={{
                      fontWeight: 700,
                      color: selectedSuspensionTypes.includes(type)
                        ? 'var(--white-color)'
                        : 'var(--main-color)',
                    }}
                  >
                    {type}
                  </span>
                </button>
              </li>
            );
          })}
        </ul>
      </section>
    );
  };

  const renderDrivetrainOptions = () => {
    return (
      <section style={{paddingLeft: 20, paddingRight: 20}}>
        <h5 style={{marginBottom: 14}}>Drivetrain</h5>
        <ul
          style={{
            display: 'flex',
            flexDirection: 'row',
            gap: 8,
            flexWrap: 'wrap',
          }}
        >
          {drivetrainOptions.map((type) => {
            return (
              <li key={type}>
                <button
                  style={{
                    height: 27,
                    paddingLeft: 20,
                    paddingRight: 20,
                    borderRadius: 30,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    border: selectedDrivetrainOptions.includes(type)
                      ? '1px solid var(--main-orange-color)'
                      : '1px solid #EEEEEE',
                    backgroundColor: selectedDrivetrainOptions.includes(type)
                      ? 'var(--main-orange-color)'
                      : 'var(--white-color)',
                  }}
                  onClick={() => handleDrivetrainOptionChange(type)}
                >
                  <span
                    className="t12"
                    style={{
                      fontWeight: 700,
                      color: selectedDrivetrainOptions.includes(type)
                        ? 'var(--white-color)'
                        : 'var(--main-color)',
                    }}
                  >
                    {type}
                  </span>
                </button>
              </li>
            );
          })}
        </ul>
      </section>
    );
  };

  const renderButton = () => {
    return (
      <section
        style={{
          padding: 20,
          position: 'fixed',
          width: '100%',
          maxWidth: 'var(--screen-width)',
          margin: '0 auto',
          bottom: 'env(safe-area-inset-bottom)',
        }}
      >
        <components.Button
          title="apply filters"
          onClick={() => {
            navigate(-1);
          }}
        />
      </section>
    );
  };

  const renderContent = () => {
    return (
      <main
        style={{
          overflowY: 'auto',
          paddingTop: 'calc(var(--header-height) + 30px)',
          paddingBottom: 110,
        }}
      >
        {renderTags()}
        {renderColors()}
        {renderBikeTypes()}
        {renderSuspensionTypes()}
        {renderDrivetrainOptions()}
      </main>
    );
  };

  return (
    <components.MotionWrapper>
      <components.SafeAreaView>
        {renderHeader()}
        {renderContent()}
        {renderButton()}
      </components.SafeAreaView>
    </components.MotionWrapper>
  );
};

// angular/spinride/src/app/screens/filter/filter.component.ts
import {Component, OnInit, signal} from '@angular/core';

import {svg} from '@svg/index';
import {MetaService} from '@services/meta.service';

@Component({
  selector: 'app-filter',
  templateUrl: './filter.component.html',
  styleUrl: './filter.component.scss',
  standalone: false,
})
export class FilterComponent implements OnInit {
  svg = svg;

  constructor(private metaService: MetaService) {}

  status = ['sale', 'new', 'top'];

  colors = [
    {id: 1, code: '#FF6262', name: 'Pastel Red'},
    {id: 2, code: '#63C7FF', name: 'Maya Blue'},
    {id: 3, code: '#F8E7CD', name: 'Champagne'},
    {id: 4, code: '#161E2F', name: 'Eigengrau'},
    {id: 5, code: '#000000', name: 'Black'},
  ];

  categories = [
    'Road Bikes',
    'Electric Bikes',
    'Hybrid Bikes',
    'Mountain Bikes',
    'Specialty Bikes',
  ];

  suspensionType = ['No Suspension', 'Front Suspension', 'Full Suspension'];

  dietaryPreferences = [
    'Vegetarian',
    'Vegan',
    'Gluten-free',
    'Nut-free',
    'Keto',
    'Low-Fat',
    'Organic',
  ];

  selectedStatus: string = this.status[1];
  selectedCategory: string = this.categories[1];
  selectedPreference: string = this.dietaryPreferences[1];

  selectedColor = signal<string | null>(null);

  selectColor(color: string): void {
    this.selectedColor.set(color);
  }

  selectCategory(category: string): void {
    this.selectedCategory = category;
  }

  selectPreference(preference: string): void {
    this.selectedPreference = preference;
  }

  selectStatus(status: string): void {
    this.selectedStatus = status;
  }

  ngOnInit(): void {
    this.setMeta();
  }

  private setMeta(): void {
    this.metaService.setThemeColor('#F3F3F3');
    this.metaService.setBackgroundColor('#F3F3F3');
  }

  resetFilters(): void {
    this.selectedStatus = this.status[0];
    // this.selectedCategory = this.categories[0];
    this.selectedPreference = this.dietaryPreferences[0];
  }
}

<app-header [showGoBack]="true" [title]="'Filter'" />

<main
  style="
    height: 100%;
    overflow-y: auto;
    margin-left: 20px;
    margin-right: 20px;
    padding-top: 10px;
    -webkit-overflow-scrolling: touch;
    scroll-behavior: smooth;
    user-select: none;
  "
>
  <!-- STATUS -->
  <section style="margin-bottom: 30px">
    <ul style="display: grid; grid-template-columns: repeat(3, 1fr)">
      <li *ngFor="let item of status; let i = index">
        <div
          style="
            display: flex;
            flex-direction: row;
            gap: 8px;
            user-select: none;
            cursor: pointer;
          "
          (click)="
            $event.stopPropagation();
            $event.preventDefault();
            selectStatus(item)
          "
        >
          <div
            style="
              width: 18px;
              height: 18px;
              border: 1px solid #eeeeee;
              border-radius: 5px;
              display: flex;
              align-items: center;
              justify-content: center;
              background-color: var(--white-color);
            "
            (click)="selectStatus(item)"
          >
            <img [src]="svg.statusSelect" *ngIf="selectedStatus === item" />
          </div>
          <div
            [ngStyle]="{
              backgroundColor:
                item === 'sale'
                  ? '#66A97D'
                  : item === 'new'
                  ? '#FF7557'
                  : '#FF6262'
            }"
            style="
              height: 19px;
              display: flex;
              align-items: center;
              justify-content: center;
              padding: 1px 6px;
              border-radius: 6px;
            "
          >
            <span
              style="
                text-transform: capitalize;
                font-size: 10px;
                text-transform: uppercase;
                color: var(--white-color);
                font-weight: 700;
              "
            >
              {{ item }}
            </span>
          </div>
        </div>
      </li>
    </ul>
  </section>

  <!-- COLOR -->
  <section style="margin-bottom: 34px">
    <h5 style="margin-bottom: 14px">Color</h5>
    <ul style="display: flex; flex-direction: row; flex-wrap: wrap; gap: 14px">
      <li
        *ngFor="let color of colors"
        style="
          display: inline-block;
          width: 30px;
          height: 30px;
          border-radius: 50%;
          display: flex;
          justify-content: center;
          align-items: center;
        "
        (click)="
          $event.stopPropagation();
          $event.preventDefault();
          selectColor(color.code)
        "
        [ngStyle]="{
          backgroundColor: color.code,
        }"
      >
        <img
          *ngIf="selectedColor() === color.code"
          [src]="svg.colorSelect"
          style="width: 16px; height: 16px"
        />
      </li>
    </ul>
  </section>

  <!-- BIKE TYPE -->
  <section>
    <h5 style="margin-bottom: 14px">Bike Type</h5>
    <ul style="display: flex; flex-direction: row; flex-wrap: wrap; gap: 8px">
      <li
        *ngFor="let item of categories"
        style="
          display: flex;
          flex-direction: row;
          gap: 8px;
          user-select: none;
          cursor: pointer;
          border: 1px solid #eeeeee;
          background-color: var(--white-color);
          padding: 5px 20px 7px 20px;
          border-radius: 30px;
        "
        [ngStyle]="{
          backgroundColor:
            selectedCategory === item
              ? 'var(--main-orange)'
              : 'var(--white-color)',
          
        }"
        (click)="
          $event.stopPropagation();
          $event.preventDefault();
          selectCategory(item)
        "
      >
        <span
          style="font-family: var(--mulish); font-weight: 700"
          [ngStyle]="{
            color: selectedCategory === item ? 'var(--white-color)' : 'var(--main-color)',
          }"
        >
          {{ item }}
        </span>
      </li>
    </ul>
  </section>
</main>

<!-- buttons -->
<section style="padding: 20px">
  <app-button
    [text]="'apply filters'"
    [containerStyle]="{'margin-bottom': '6px'}"
    [routerLink]="'/shop'"
  />
</section>
